name: Gradle

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: MongoDB in GitHub Actions
        uses: supercharge/mongodb-github-action@1.3.0

      - name: setup
        run: chmod +x gradlew

      - name: test
        run: ./gradlew test

      - name: Build with Gradle
        run: ./gradlew build

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish package
        if: github.ref == 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew publish

